apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv03
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "/mnt/data/efk03" #host location
